In [1]:
import numpy as np

Crear un vector con valores dentro del rango 10 a 49

In [2]:
array_1 = np.arange(10, 50)
print(array_1)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


### Invertir el vector

In [3]:
array_1[::1]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

### Crear una matriz 3x3 con valores de 0 a 8

In [4]:
array_2 = np.arange(9).reshape(3, 3)
print(array_2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### Encontrar los indices que no son ceros del arreglo [1,2,4,2,4,0,1,0,0,0,12,4,5,6,7,0]

In [5]:
array_3 = np.array([1,2,4,2,4,0,1,0,0,0,12,4,5,6,7,0])
print(np.where(array_3 != 0)[0])

[ 0  1  2  3  4  6 10 11 12 13 14]


### Crear una matriz identidad de 6x6

In [6]:
array_4 = np.identity(6)
print(array_4)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


### Crear una matriz con valores al azar con forma 3x3x3 

In [7]:
array_5 = np.random.randint(89, size = (3, 3, 3))
print(array_5)

[[[86 11 78]
  [54 19 12]
  [61 39 15]]

 [[86 23 24]
  [ 9 44 68]
  [14 76 40]]

 [[73 61 26]
  [ 0 87 62]
  [ 0 20 25]]]


### Encontrar los indices de los valores minimos y maximos de la anterior matriz

In [8]:
x = np.argmin(array_5)
x = np.unravel_index(x, (3, 3, 3))
print('Indice:', x)
print(f'Matriz: {x[0]}\nFila: {x[1]}\nColumna: {x[2]}')

Indice: (2, 1, 0)
Matriz: 2
Fila: 1
Columna: 0


### Crear una matriz de 10x10 con 1's en los bordes y 0 en el interior (con rangos de indices)

In [9]:
array_6 = np.full((10, 10), 1)
array_6[1:9, 1:9] = 0
print(array_6)


[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


### Crear una matriz de 5x5 con valores en los renglones que vayan de 0 a 4

In [10]:
array_7 = np.random.randint(5, size = (5, 5))
print(array_7)

[[1 2 3 1 0]
 [4 4 4 2 1]
 [1 0 4 2 4]
 [4 3 4 2 4]
 [1 3 3 0 2]]


### Crear dos arreglos al azar A y B, verificar si son iguales

In [11]:
array_A = np.random.rand(3, 3)
array_B = np.random.rand(3, 3)

print(array_A, array_B, sep = '\n\n')

array_A == array_B

[[0.88578974 0.85885404 0.20799025]
 [0.67907531 0.30218213 0.92912413]
 [0.59306324 0.65463182 0.54022075]]

[[0.705571   0.00282775 0.13304087]
 [0.3110148  0.11562388 0.31422905]
 [0.8005957  0.52845478 0.95552083]]


array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [20]:
np.allclose(array_A, array_B, rtol = 0.5)

False

In [27]:
a = np.array([0.5, 0.6, 0.7])
b = np.array([0.5, 0.6, 0.8])

np.allclose(a, b, rtol = 0.2)

True